In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [46]:
df = pd.read_csv(r"/Users/sandhya/Library/Containers/com.microsoft.Excel/Data/Downloads/archive (1)/BooksDataset.csv")

In [47]:
df

,Title,Authors,Description,Category,Publisher,Publish Date,Price
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
1,The Missing Person,"By Grumbach, Doris",NaN,"Fiction , General",Putnam Pub Group,"Sunday, March 1, 1981",Price Starting at $4.99
2,Don't Eat Your Heart Out Cookbook,"By Piscatella, Joseph C.",NaN,"Cooking , Reference",Workman Pub Co,"Thursday, September 1, 1983",Price Starting at $4.99
3,When Your Corporate Umbrella Begins to Leak: A...,"By Davis, Paul D.",NaN,NaN,Natl Pr Books,"Monday, April 1, 1991",Price Starting at $4.99
4,Amy Spangler's Breastfeeding : A Parent's Guide,"By Spangler, Amy",NaN,NaN,Amy Spangler,"Saturday, February 1, 1997",Price Starting at $5.32
...,...,...,...,...,...,...,...
103077,Build 3 Super Serving Carts,By Chuck Hampton,NaN,NaN,ENDesigns Inc.,"Wednesday, January 1, 1992",Price Starting at $9.97
103078,My Land of Israel,"By Nover, Elizabeth Z.",NaN,"Juvenile Nonfiction , People & Places , Middl...",Behrman House,"Friday, May 1, 1987",Price Starting at $4.99
103079,Tongues: To Speak or Not to Speak,By Donald W. Burdick,NaN,NaN,Moody Press,"Wednesday, January 1, 1969",Price Starting at $5.29
103080,If I'm in charge here why is everybody laughing?,"By Campbell, David P.",NaN,NaN,Argus Communications,"Tuesday, January 1, 1980",Price Starting at $4.99
103081,Your First Puppy (Your First Series),"By Carpentier, Marcel",An introduction to the proper care of puppies ...,"Pets , Dogs , General",Tfh Pubns Inc,"Friday, November 1, 1991",Price Starting at $4.99

In [48]:
df[df['Publisher'] == 'Doubleday']

,Title,Authors,Description,Category,Publisher,Publish Date,Price
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
39,Joshua and the City,"By Girzone, Joseph F.",A contemporary city faces turmoil and devastat...,"Religion , Inspirational",Doubleday,"Wednesday, March 1, 1995",Price Starting at $5.29
307,The Art of Cooking with Herbs & Spices,"By Miloradovich, Milo",NaN,NaN,Doubleday,"Sunday, January 1, 1950",Price Starting at $5.29
322,Inference of guilt,"By Greene, Harris",NaN,NaN,Doubleday,"Friday, January 1, 1982",Price Starting at $36.20
462,A Prophet In His Own Country: The Triumphs and...,By Kenneth S. Davis,NaN,NaN,Doubleday,"Tuesday, January 1, 1957",Price Starting at $36.61
...,...,...,...,...,...,...,...
102493,The Nobodies Album: A Novel,"By Parkhurst, Carolyn",From the bestselling author of The Dogs of Bab...,"Fiction , Mystery & Detective , General",Doubleday,"Tuesday, June 1, 2010",Price Starting at $4.99
102607,"Only 25 Recipies You'll Ever Need, The","By Burstein, Sidney and Mitchell, Celia (ILT)","Includes twenty-five basic recipes that, with ...","Cooking , Reference",Doubleday,"Tuesday, May 1, 1990",Price Starting at $5.29
102652,The Futurist: A Novel,"By Othmer, James P.","Yates is a Futurist. Which is to say, he makes...","Fiction , General",Doubleday,"Thursday, June 1, 2006",Price Starting at $4.89
102739,The Company of Animals: 20 Stories of Alliance...,"By Rosen, Michael J. (EDT)","Twenty stories, by such writers as Italo Calvi...","Fiction , General",Doubleday,"Friday, October 1, 1993",Price Starting at $4.99
103065,Crafts of Mexico (Crafts of the world),"By Sayer, Chloe",Describes the historical background and the ma...,"Crafts & Hobbies , General",Doubleday,"Thursday, September 1, 1977",Price Starting at $4.99

In [49]:
specific_Authors = ['By Colton, Larry' , 'By Othmer, James P.']
df[df['Authors'].isin(specific_Authors)]

,Title,Authors,Description,Category,Publisher,Publish Date,Price
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
102652,The Futurist: A Novel,"By Othmer, James P.","Yates is a Futurist. Which is to say, he makes...","Fiction , General",Doubleday,"Thursday, June 1, 2006",Price Starting at $4.89

In [50]:
df[df['Authors'].str.contains('Larry')]

,Title,Authors,Description,Category,Publisher,Publish Date,Price
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
72,Sherlock Holmes and the Red Demon by John H. W...,"By Watson, John H. and Millett, Larry (EDT)",It is the story of how the world's most belove...,"Fiction , Mystery & Detective , General",Viking,"Sunday, September 1, 1996",Price Starting at $4.99
601,The World's Whales: The Complete Illustrated G...,"By Balcomb, Kenneth C., Foster, Larry, and Min...",This encyclopedic field guide to the eighty-se...,"Science , General",Smithsonian Inst Pr,"Monday, October 1, 1984",Price Starting at $10.99
717,Communications and Networking for the IBM PC a...,"By Jordan, Larry E",Covers the fundamentals and applications of da...,NaN,Brady Publishing,"Thursday, October 1, 1987",Price Starting at $6.60
1420,The Action Heroine's Handbook,"By Borgenicht, Joe, Worick, Jennifer, and Jost...",Get Some Action! Â For every woman who wants t...,"Reference , Personal & Practical Guides",Quirk Books,"Wednesday, October 1, 2003",Price Starting at $5.29
...,...,...,...,...,...,...,...
101341,Programming Perl,"By Potter, Stephen, Schwartz, Randal L., Chris...","Programming Perl, 2nd Edition is the authorita...","Computers , Operating Systems , UNIX",O'Reilly Media,"Friday, November 1, 1996",Price Starting at $8.79
101499,Ahead of the Curve: The Power of Assessment to...,"By Ainsworth, Larry, Dufour, Richard, Almeida,...",This anthology brings the ideas and recommenda...,"Education , Educational Policy & Reform , Gen...",Solution Tree,"Saturday, September 1, 2007",Price Starting at $5.64
101512,Travelers' Tales Thailand: True Stories,"By Habegger, Larry (EDT) and O'Reilly, James (...",Winner of the Lowell Thomas Award for Best Tra...,"Travel , Asia , Southeast",Travelers' Tales,"Friday, February 1, 2002",Price Starting at $5.29
101646,Following the Law: The Total Tricks Sequel,"By Cohen, Larry",NaN,"Games , General",Natco Press,"Saturday, October 1, 1994",Price Starting at $5.29
102770,Musician's Guide to Home Tape Recording,"By McIan, Peter and Wichman, Larry",NaN,"Music , Recording & Reproduction",Fireside,"Thursday, September 1, 1988",Price Starting at $10.99

In [51]:
df2 = df.set_index('Authors')

In [52]:
df2

,Title,Description,Category,Publisher,Publish Date,Price
Authors,,,,,,
"By Colton, Larry",Goat Brothers,NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
"By Grumbach, Doris",The Missing Person,NaN,"Fiction , General",Putnam Pub Group,"Sunday, March 1, 1981",Price Starting at $4.99
"By Piscatella, Joseph C.",Don't Eat Your Heart Out Cookbook,NaN,"Cooking , Reference",Workman Pub Co,"Thursday, September 1, 1983",Price Starting at $4.99
"By Davis, Paul D.",When Your Corporate Umbrella Begins to Leak: A...,NaN,NaN,Natl Pr Books,"Monday, April 1, 1991",Price Starting at $4.99
"By Spangler, Amy",Amy Spangler's Breastfeeding : A Parent's Guide,NaN,NaN,Amy Spangler,"Saturday, February 1, 1997",Price Starting at $5.32
...,...,...,...,...,...,...
By Chuck Hampton,Build 3 Super Serving Carts,NaN,NaN,ENDesigns Inc.,"Wednesday, January 1, 1992",Price Starting at $9.97
"By Nover, Elizabeth Z.",My Land of Israel,NaN,"Juvenile Nonfiction , People & Places , Middl...",Behrman House,"Friday, May 1, 1987",Price Starting at $4.99
By Donald W. Burdick,Tongues: To Speak or Not to Speak,NaN,NaN,Moody Press,"Wednesday, January 1, 1969",Price Starting at $5.29
"By Campbell, David P.",If I'm in charge here why is everybody laughing?,NaN,NaN,Argus Communications,"Tuesday, January 1, 1980",Price Starting at $4.99
"By Carpentier, Marcel",Your First Puppy (Your First Series),An introduction to the proper care of puppies ...,"Pets , Dogs , General",Tfh Pubns Inc,"Friday, November 1, 1991",Price Starting at $4.99

In [53]:
df2.filter(items = ['Title' ,'Description'])

,Title,Description
Authors,,
"By Colton, Larry",Goat Brothers,NaN
"By Grumbach, Doris",The Missing Person,NaN
"By Piscatella, Joseph C.",Don't Eat Your Heart Out Cookbook,NaN
"By Davis, Paul D.",When Your Corporate Umbrella Begins to Leak: A...,NaN
"By Spangler, Amy",Amy Spangler's Breastfeeding : A Parent's Guide,NaN
...,...,...
By Chuck Hampton,Build 3 Super Serving Carts,NaN
"By Nover, Elizabeth Z.",My Land of Israel,NaN
By Donald W. Burdick,Tongues: To Speak or Not to Speak,NaN
"By Campbell, David P.",If I'm in charge here why is everybody laughing?,NaN
"By Carpentier, Marcel",Your First Puppy (Your First Series),An introduction to the proper care of puppies ...

In [54]:
df[df['Authors'].str.contains('Larry')].sort_values(by = 'Authors' , ascending =True)

,Title,Authors,Description,Category,Publisher,Publish Date,Price
76913,Jesus ; The Gift of Hope,"By Abraham, Ken, Illustrated by Larry Lawson",NaN,NaN,1995: Warner Books,"Sunday, January 1, 1995",Price Starting at $5.29
1453,The Patterns of War Since the Eighteenth Century,"By Addington, Larry H.",This important work... synthesizes the evoluti...,"Technology & Engineering , Military Science",Indiana University Press,"Saturday, October 1, 1994",Price Starting at $4.99
101499,Ahead of the Curve: The Power of Assessment to...,"By Ainsworth, Larry, Dufour, Richard, Almeida,...",This anthology brings the ideas and recommenda...,"Education , Educational Policy & Reform , Gen...",Solution Tree,"Saturday, September 1, 2007",Price Starting at $5.64
87055,Balanced Healing: Combining Modern Medicine wi...,"By Altshuler, Larry",A comprehensive reference guide to alternative...,"Health & Fitness , Healing","Harbor Press, Inc.","Monday, December 1, 2003",Price Starting at $6.13
64504,Now You're Talking!: All You Need to Get Your ...,"By American Radio Relay League (COR), Kleinman...",NaN,"Crafts & Hobbies , Reference",Amer Radio Relay League,"Tuesday, April 1, 1997",Price Starting at $10.99
...,...,...,...,...,...,...,...
88851,Daughter of China : A True Story of Love and B...,"By Xu, Meihong and Engelmann, Larry","This is the story of Meihong Xu, a woman train...","Biography & Autobiography , General",Headline Book Pub Ltd,"Monday, May 1, 2000",Price Starting at $5.29
87208,Daughter of China: A True Story of Love and Be...,"By Xu, Meihong and Engelmann, Larry",The critically acclaimed memoir of a forbidden...,"Biography & Autobiography , Political",Wiley,"Wednesday, September 1, 1999",Price Starting at $5.76
32488,The 47 Best Chocolate Chip Cookies in the Worl...,"By Zisman, Larry and Zisman, Honey",Chocolate chip cookies are a true American del...,"Cooking , Courses & Dishes , Cookies",Griffin,"Saturday, October 1, 1983",Price Starting at $5.29
94851,The 50 Best Cheesecakes in the World: The Winn...,"By Zisman, Larry and Zisman, Honey","If you're passionate about cheesecake, you'll ...","Cooking , Courses & Dishes , Cakes",St. Martin's Griffin,"Tuesday, June 1, 1993",Price Starting at $5.29
2489,I'll Never Have Sex with You Again!: Tales fro...,"By Zutell, Irene and Bleidner, Larry",FORGET EVERYTHING YOU THINK YOU KNOW ABOUT CHI...,"Health & Fitness , Pregnancy & Childbirth",Touchstone,"Wednesday, May 1, 2002",Price Starting at $5.29

Lambda function

In [55]:
df.head()

,Title,Authors,Description,Category,Publisher,Publish Date,Price
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79
1,The Missing Person,"By Grumbach, Doris",NaN,"Fiction , General",Putnam Pub Group,"Sunday, March 1, 1981",Price Starting at $4.99
2,Don't Eat Your Heart Out Cookbook,"By Piscatella, Joseph C.",NaN,"Cooking , Reference",Workman Pub Co,"Thursday, September 1, 1983",Price Starting at $4.99
3,When Your Corporate Umbrella Begins to Leak: A...,"By Davis, Paul D.",NaN,NaN,Natl Pr Books,"Monday, April 1, 1991",Price Starting at $4.99
4,Amy Spangler's Breastfeeding : A Parent's Guide,"By Spangler, Amy",NaN,NaN,Amy Spangler,"Saturday, February 1, 1997",Price Starting at $5.32

In [56]:
df['Publish Date'].unique()

array(['Friday, January 1, 1993', 'Sunday, March 1, 1981',
       'Thursday, September 1, 1983', 'Monday, April 1, 1991',
       'Saturday, February 1, 1997', 'Wednesday, January 1, 1997',
       'Saturday, May 1, 1993', 'Saturday, September 1, 2001',
       'Monday, June 1, 1987', 'Sunday, June 1, 1986',
       'Sunday, January 1, 1978', 'Monday, October 1, 2001',
       'Sunday, September 1, 1996', 'Friday, May 1, 1998',
       'Tuesday, September 1, 1998', 'Monday, January 1, 1979',
       'Thursday, January 1, 1998', 'Tuesday, January 1, 1991',
       'Monday, October 1, 1990', 'Wednesday, April 1, 1992',
       'Friday, February 1, 1991', 'Saturday, January 1, 1994',
       'Tuesday, May 1, 1979', 'Friday, October 1, 1993',
       'Tuesday, August 1, 1961', 'Saturday, May 1, 1999',
       'Saturday, October 1, 1994', 'Sunday, January 1, 1995',
       'Saturday, March 1, 1997', 'Saturday, November 1, 2003',
       'Thursday, January 1, 1987', 'Thursday, January 1, 2004',
       'Tuesday, October 1, 2002', 'Tuesday, November 1, 1994',
       'Thursday, June 1, 2000', 'Sunday, March 1, 1998',
       'Wednesday, March 1, 1995', 'Monday, September 1, 1997',
       'Friday, December 1, 2000', 'Sunday, November 1, 1992',
       'Monday, October 1, 1984', 'Tuesday, January 1, 2002',
       'Saturday, July 1, 1995', 'Thursday, February 1, 2001',
       'Wednesday, February 1, 1989', 'Friday, January 1, 1982',
       'Friday, August 1, 1980', 'Sunday, August 1, 1993',
       'Saturday, June 1, 2002', 'Wednesday, January 1, 1964',
       'Sunday, October 1, 1972', 'Friday, January 1, 1965',
       'Saturday, April 1, 1989', 'Sunday, October 1, 1995',
       'Monday, September 1, 1975', 'Saturday, June 1, 1996',
       'Wednesday, October 1, 1997', 'Wednesday, October 1, 1986',
       'Monday, February 1, 1993', 'Sunday, June 1, 2003',
       'Thursday, July 1, 1982', 'Monday, January 1, 1951',
       'Thursday, January 1, 1948', 'Wednesday, January 1, 1947',
       'Sunday, September 1, 1985', 'Sunday, September 1, 2002',
       'Monday, January 1, 1973', 'Saturday, August 1, 1987',
       'Monday, January 1, 2001', 'Tuesday, January 1, 1974',
       'Tuesday, March 1, 1983', 'Saturday, January 1, 1983',
       'Friday, September 1, 1989', 'Monday, September 1, 2003',
       'Friday, June 1, 2001', 'Monday, January 1, 1945',
       'Wednesday, October 1, 2003', 'Saturday, February 1, 2003',
       'Monday, September 1, 1986', 'Friday, January 1, 1999',
       'Wednesday, August 1, 1990', 'Friday, September 1, 1995',
       'Wednesday, November 1, 1995', 'Tuesday, October 1, 1985',
       'Tuesday, February 1, 2000', 'Thursday, August 1, 1991',
       'Friday, March 1, 1996', 'Thursday, April 1, 1993',
       'Friday, February 1, 2002', 'Friday, July 1, 1983',
       'Thursday, November 1, 1979', 'Monday, March 1, 2004',
       'Saturday, January 1, 2000', 'Thursday, May 1, 1986',
       'Sunday, January 1, 1967', 'Tuesday, September 1, 1987',
       'Friday, May 1, 1992', 'Wednesday, February 1, 1984',
       'Tuesday, October 1, 1991', 'Sunday, April 1, 1990',
       'Wednesday, July 1, 1992', 'Sunday, January 1, 1956',
       'Wednesday, May 1, 1985', 'Tuesday, June 1, 1993',
       'Saturday, September 1, 1990', 'Saturday, April 1, 2000',
       'Tuesday, October 1, 1996', 'Thursday, November 1, 2001',
       'Thursday, December 1, 1994', 'Saturday, April 1, 1995',
       'Monday, March 1, 1999', 'Tuesday, May 1, 2001',
       'Friday, October 1, 2004', 'Saturday, October 1, 1988',
       'Saturday, January 1, 1977', 'Wednesday, November 1, 2000',
       'Monday, April 1, 1996', 'Monday, January 1, 1996',
       'Sunday, July 1, 2001', 'Tuesday, November 1, 1988',
       'Monday, December 1, 1997', 'Friday, September 1, 2000',
       'Tuesday, June 1, 1999', 'Sunday, January 1, 1950',
       'Sunday, December 1, 1991', 'Sunday, April 1, 1962',
       'Friday, January 1, 1960', 'Thursday, March 1, 1984',
       'Thursday, April 1, 2004', 'Sunday, January 1, 1989',
       'Thursday, February 1, 1996', 'Friday, November 1, 1991',
       'Friday, June 1, 1973', 'Friday, November 1, 1996',
       'Wednesday, January 1, 1975', 'Monday, June 1, 1992',
       'Monday, January 1, 1990', 'Thursday, November 1, 1984',
       'Monday, July 1, 1991', 'Thursday, January 1, 1981',
       'Friday, January 1, 1954', 'Saturday, May 1, 1976',
       'Wednesday, June 1, 1983', 'Thursday, January 1, 1976',
       'Saturday, November 1, 1969', 'Thursday, October 1, 1992',
       'Monday, February 1, 1999', 'Wednesday, April 1, 1998',
       'Sunday, May 1, 1988', 'Monday, May 1, 2000',
       'Wednesday, January 1, 1992', 'Friday, January 1, 1988',
       'Tuesday, June 1, 1976', 'Saturday, January 1, 1949',
       'Thursday, November 1, 1973', 'Monday, January 1, 1962',
       'Wednesday, January 1, 1958', 'Saturday, August 1, 1992',
       'Wednesday, June 1, 1994', 'Saturday, November 1, 1980',
       'Sunday, September 1, 1991', 'Monday, May 1, 1995',
       'Monday, July 1, 2002', 'Friday, January 1, 1932',
       'Friday, May 1, 1987', 'Sunday, June 1, 1975',
       'Tuesday, December 1, 1992', 'Thursday, October 1, 1987',
       'Sunday, October 1, 1989', 'Wednesday, May 1, 1996',
       'Tuesday, September 1, 1959', 'Monday, January 1, 1968',
       'Sunday, August 1, 2004', 'Thursday, February 1, 1990',
       'Thursday, September 1, 1994', 'Thursday, September 1, 1988',
       'Saturday, January 1, 1955', 'Thursday, January 1, 1925',
       'Wednesday, April 1, 1987', 'Thursday, June 1, 1995',
       'Saturday, May 1, 2004', 'Tuesday, April 1, 1997',
       'Thursday, July 1, 1999', 'Friday, October 1, 1999',
       'Wednesday, May 1, 2013', 'Monday, March 1, 1993',
       'Friday, November 1, 1985', 'Friday, June 1, 1984',
       'Sunday, January 1, 1984', 'Wednesday, February 1, 1995',
       'Monday, May 1, 1989', 'Tuesday, February 1, 1994',
       'Thursday, May 1, 1997', 'Sunday, December 1, 1996',
       'Monday, November 1, 1976', 'Thursday, January 1, 1970',
       'Sunday, December 1, 1985', 'Thursday, March 1, 2001',
       'Monday, June 1, 1981', 'Sunday, June 1, 1969',
       'Wednesday, September 1, 1999', 'Saturday, November 1, 2008',
       'Friday, October 1, 1971', 'Tuesday, February 1, 1983',
       'Friday, July 1, 2005', 'Saturday, December 1, 1990',
       'Wednesday, June 1, 1977', 'Thursday, November 1, 1990',
       'Monday, June 1, 1998', 'Tuesday, July 1, 2003',
       'Monday, August 1, 1994', 'Sunday, February 1, 2004',
       'Sunday, November 1, 1998', 'Wednesday, March 1, 2000',
       'Saturday, September 1, 1984', 'Friday, January 1, 1971',
       'Saturday, November 1, 1997', 'Wednesday, May 1, 2002',
       'Wednesday, December 1, 2004', 'Friday, December 1, 1995',
       'Wednesday, July 1, 1987', 'Friday, April 1, 1994',
       'Sunday, January 1, 1961', 'Thursday, August 1, 2002',
       'Tuesday, March 1, 1994', 'Tuesday, September 1, 1981',
       'Sunday, March 1, 1992', 'Tuesday, June 1, 1971',
       'Wednesday, January 1, 1986', 'Thursday, March 1, 1990',
       'Wednesday, November 1, 1989', 'December 1899',
       'Friday, August 1, 1986', 'Saturday, February 1, 1992',
       'Sunday, May 1, 1994', 'Sunday, December 1, 2002',
       'Sunday, August 1, 1982', 'Thursday, July 1, 1993',
       'Wednesday, June 1, 2005', 'Saturday, December 1, 1984',
       'Wednesday, August 1, 2001', 'Wednesday, December 1, 1999',
       'Tuesday, August 1, 1995', 'Friday, March 1, 2002',
       'Sunday, April 1, 1973', 'Sunday, December 1, 2019',
       'Tuesday, January 1, 1957', 'Tuesday, March 1, 2005',
       'Wednesday, January 1, 2003', 'Sunday, August 1, 1976',
       'Monday, October 1, 1979', 'Saturday, December 1, 2018',
       'Monday, June 1, 1953', 'Tuesday, January 1, 1985',
       'Sunday, January 1, 1933', 'Saturday, June 1, 1991',
       'Sunday, June 1, 1952', 'Saturday, January 1, 1966',
       'Sunday, October 1, 1978', 'Sunday, October 1, 2000',
       'Tuesday, July 1, 1997', 'Wednesday, May 1, 1991',
       'Tuesday, January 1, 1980', 'Tuesday, August 1, 1989',
       'Wednesday, January 1, 1936', 'Friday, December 1, 1989',
       'Tuesday, May 1, 1984', 'Sunday, May 1, 2005',
       'Saturday, August 1, 1998', 'Wednesday, January 1, 1969',
       'Sunday, August 1, 1999', 'Wednesday, July 1, 1998',
       'Sunday, November 1, 1987', 'Monday, July 1, 1996',
       'Wednesday, June 1, 1988', 'Tuesday, August 1, 2000',
       'Saturday, December 1, 2001', 'Wednesday, April 1, 1981',
       'Thursday, January 1, 1942', 'Monday, November 1, 1993',
       'Friday, March 1, 1991', 'Sunday, June 1, 1997',
       'Thursday, May 1, 2003', 'Wednesday, December 1, 1993',
       'Saturday, July 1, 1989', 'Wednesday, September 1, 1976',
       'Thursday, December 1, 1988', 'Saturday, June 1, 1974',
       'Friday, November 1, 2002', 'Monday, December 1, 2003',
       'Thursday, March 1, 1973', 'Tuesday, April 1, 1986',
       'Thursday, May 1, 1980', 'Tuesday, March 1, 1988',
       'Friday, March 1, 1985', 'Saturday, July 1, 2000',
       'Friday, April 1, 1988', 'Tuesday, April 1, 1980',
       'Saturday, January 1, 1972', 'Monday, November 1, 1999',
       'Wednesday, October 1, 1969', 'Wednesday, September 1, 1993',
       'Thursday, August 1, 1996', 'Thursday, October 1, 1998',
       'Tuesday, December 1, 1998', 'Thursday, July 1, 2004',
       'Sunday, April 1, 2001', 'Thursday, April 1, 1982',
       'Sunday, June 1, 1980', 'Wednesday, December 1, 1976',
       'Sunday, April 1, 1979', 'Friday, January 1, 1943',
       'Sunday, April 1, 1984', 'Saturday, October 1, 1983',
       'Friday, October 1, 1982', 'Wednesday, February 1, 1967',
       'Saturday, February 1, 1986', 'Friday, July 1, 1994',
       'Monday, February 1, 1988', 'Sunday, February 1, 1998',
       'Friday, July 1, 1988', 'Saturday, March 1, 2003',
       'Friday, August 1, 2003', 'Monday, April 1, 2002',
       'Tuesday, October 1, 1974', 'Saturday, June 1, 1985',
       'Thursday, October 1, 1981', 'Thursday, December 1, 1983',
       'Thursday, June 1, 1989', 'Sunday, July 1, 1990',
       'Wednesday, October 1, 1975', 'Tuesday, April 1, 2003',
       'Thursday, March 1, 1979', 'Wednesday, March 1, 1989',
       'Tuesday, July 1, 1986', 'Tuesday, December 1, 1987',
       'Wednesday, June 1, 1966', 'Tuesday, September 1, 1992',
       'Tuesday, January 1, 1946', 'Wednesday, October 1, 1980',
       'Saturday, November 1, 1975', 'Friday, December 1, 1972',
       'Friday, November 1, 1974', 'Sunday, March 1, 1987',
       'Friday, April 1, 1983', 'Wednesday, September 1, 2004',
       'Friday, August 1, 1997', 'Saturday, December 1, 1979',
       'Thursday, June 1, 1978', 'Thursday, June 1, 1967',
       'Tuesday, November 1, 1983', 'Tuesday, May 1, 1990',
       'Monday, August 1, 1988', 'Friday, June 1, 1979',
       'Tuesday, June 1, 2004', 'Monday, August 1, 1977',
       'Monday, August 1, 1955', 'Thursday, January 1, 1953',
       'Saturday, January 1, 2005', 'Sunday, January 1, 1939',
       'Friday, February 1, 1974', 'Friday, February 1, 1980',
       'Sunday, March 1, 2020', 'Thursday, April 1, 1999',
       'Friday, September 1, 1978', 'Tuesday, April 1, 1975',
       'Thursday, September 1, 2005', 'Sunday, January 1, 2006',
       'Saturday, October 1, 2005', 'Tuesday, February 1, 2005',
       'Friday, April 1, 2005', 'Tuesday, April 1, 1969',
       'Thursday, January 1, 1959', 'Monday, August 1, 1983',
       'Monday, August 1, 2005', 'Monday, November 1, 2004',
       'Sunday, February 1, 1976', 'Tuesday, January 1, 1963',
       'Sunday, January 1, 1900', 'Wednesday, December 1, 1982',
       'Saturday, August 1, 2009', 'Monday, April 1, 1968',
       'Monday, September 1, 1980', 'Saturday, September 1, 1973',
       'Wednesday, April 1, 2015', 'Saturday, April 1, 2006',
       'Thursday, December 1, 2005', 'Sunday, February 1, 2009',
       'Sunday, July 1, 1984', 'Monday, February 1, 1965',
       'Saturday, July 1, 2006', 'Saturday, January 1, 1938',
       'Thursday, December 1, 1977', 'Friday, June 1, 1990',
       'Monday, January 1, 1940', 'Friday, March 1, 1963',
       'Sunday, March 1, 1970', 'Sunday, February 1, 1987',
       'Wednesday, December 1, 1954', 'Tuesday, November 1, 2005',
       'Friday, June 1, 2007', 'Wednesday, September 1, 1971',
       'Monday, June 1, 1970', 'Monday, March 1, 1976',
       'Tuesday, July 1, 1980', 'Sunday, February 1, 2015',
       'Monday, February 1, 1982', 'Thursday, September 1, 1960',
       'Saturday, June 1, 1968', 'Friday, May 1, 1981',
       'Wednesday, August 1, 1979', 'Tuesday, June 1, 2010',
       'Friday, October 1, 1976', 'Wednesday, August 1, 1984',
       'Wednesday, July 1, 2009', 'Tuesday, June 1, 1954',
       'Tuesday, September 1, 2009', 'Tuesday, March 1, 1977',
       'Thursday, July 1, 1971', 'Wednesday, September 1, 1982',
       'Sunday, August 1, 1971', 'Sunday, February 1, 1970',
       'Wednesday, February 1, 2006', 'Tuesday, August 1, 1978',
       'Wednesday, May 1, 1974', 'Saturday, July 1, 1978',
       'Monday, May 1, 1978', 'Wednesday, April 1, 1970',
       'Friday, September 1, 1972', 'Wednesday, March 1, 2006',
       'Saturday, May 1, 1982', 'Wednesday, January 1, 1930',
       'Thursday, June 1, 2006', 'Monday, November 1, 1971',
       'Saturday, November 1, 1986', 'Monday, September 1, 1969',
       'Tuesday, November 1, 2011', 'Friday, June 1, 2012',
       'Tuesday, January 1, 1952', 'Tuesday, November 1, 1977',
       'Wednesday, November 1, 1978', 'Friday, January 1, 2010',
       'Monday, March 1, 1982', 'Monday, July 1, 1963',
       'Monday, December 1, 1986', 'Monday, July 1, 1985',
       'Tuesday, January 1, 1935', 'Monday, May 1, 1972',
       'Wednesday, July 1, 1981', 'Friday, December 1, 1961',
       'Sunday, September 1, 1974', 'Monday, March 1, 1971',
       'Friday, December 1, 2006', 'Friday, October 1, 1965',
       'Saturday, June 1, 1957', 'Thursday, June 1, 1972',
       'Tuesday, June 1, 1982', 'Saturday, July 1, 1905',
       'Sunday, May 1, 1983', 'Saturday, August 1, 1981',
       'Monday, October 1, 1973', 'January 1880', 'Monday, June 1, 1964',
       'Thursday, August 1, 1974', 'Sunday, July 1, 1979',
       'Monday, November 1, 1982', 'Monday, May 1, 2006',
       'Thursday, May 1, 1975', 'Tuesday, May 1, 1973',
       'Monday, April 1, 1985', 'Friday, December 1, 1978',
       'Thursday, August 1, 1985', 'Saturday, March 1, 1986',
       'Tuesday, February 1, 1972', 'Saturday, February 1, 1975',
       'Thursday, September 1, 1977', 'Saturday, April 1, 1978',
       'Sunday, December 1, 1974', 'Tuesday, November 1, 1966',
       'Saturday, September 1, 1979', 'Saturday, March 1, 1980',
       'Thursday, April 1, 1971', 'Monday, December 1, 1980',
       'Wednesday, October 1, 2008', 'Monday, December 1, 1975',
       'Friday, April 1, 1977', 'Wednesday, March 1, 1978',
       'Friday, February 1, 1985', 'Thursday, July 1, 1976',
       'Sunday, February 1, 1981', 'Wednesday, February 1, 1978',
       'Thursday, February 1, 1979', 'Friday, July 1, 1977',
       'Saturday, October 1, 1977', 'Wednesday, May 1, 1963',
       'Wednesday, March 1, 1972', 'Monday, April 1, 1974',
       'Monday, March 1, 1965', 'Saturday, March 1, 1975',
       'Thursday, April 1, 1976', 'Friday, March 1, 1974',
       'Sunday, May 1, 1960', 'Friday, July 1, 1960',
       'Sunday, November 1, 1970', 'Saturday, April 1, 1967',
       'Sunday, November 1, 1981', 'Sunday, June 1, 2014',
       'Friday, May 1, 1970', 'Tuesday, December 1, 1981',
       'Tuesday, June 1, 1965', 'Monday, July 1, 1974',
       'Wednesday, August 1, 1973', 'Monday, June 1, 1959',
       'Sunday, October 1, 1967', 'Saturday, September 1, 2007',
       'Sunday, May 1, 1977', 'Tuesday, September 1, 1970',
       'Saturday, January 1, 1944', 'Monday, January 1, 1934',
       'Thursday, June 1, 1961', 'Tuesday, August 1, 1972',
       'Tuesday, January 1, 2019', 'Saturday, July 1, 1967',
       'Friday, August 1, 2008', 'Saturday, December 1, 1962',
       'Wednesday, January 1, 1941', 'January 1852',
       'Tuesday, September 1, 2020', 'Saturday, June 1, 2019',
       'Sunday, January 1, 2017', 'Sunday, April 1, 2012',
       'Monday, June 1, 2009', 'Thursday, October 1, 1959',
       'Saturday, September 1, 1962', 'Monday, January 1, 2007',
       'Monday, July 1, 2013', 'Thursday, April 1, 1965',
       'Thursday, January 1, 1903', 'Tuesday, August 1, 2006',
       'January 1865', 'Wednesday, June 1, 1955',
       'Saturday, December 1, 1973', 'Tuesday, April 1, 1958',
       'Tuesday, December 1, 1970', 'Thursday, May 1, 2008',
       'Sunday, July 1, 1973', 'Saturday, April 1, 1972',
       'Friday, June 1, 1956', 'Tuesday, October 1, 2013', 'January 1864',
       'Friday, October 1, 1954', 'Wednesday, August 1, 2007',
       'Friday, August 1, 1975', 'Friday, September 1, 2006',
       'Friday, October 1, 2010', 'Saturday, October 1, 2011',
       'Wednesday, June 1, 1960', 'Sunday, June 1, 2008',
       'Monday, April 1, 2019', 'Saturday, January 1, 1927',
       'Thursday, February 1, 1968', 'Saturday, March 1, 1969',
       'Sunday, December 1, 1968', 'Monday, January 1, 1917',
       'Friday, January 1, 1937', 'Tuesday, January 1, 1929',
       'Tuesday, January 1, 2013', 'Tuesday, April 1, 2008',
       'Tuesday, September 1, 2015', 'Thursday, March 1, 1951',
       'Tuesday, January 1, 2008', 'Friday, February 1, 2008',
       'Sunday, March 1, 2015', 'Sunday, December 1, 1963',
       'Monday, June 1, 2015', 'Wednesday, November 1, 1972',
       'Tuesday, February 1, 1966', 'Wednesday, February 1, 2012',
       'Saturday, January 1, 2022', 'Thursday, February 1, 2018',
       'Thursday, November 1, 2012', 'Tuesday, March 1, 2016',
       'Monday, August 1, 1966', 'Saturday, November 1, 1958',
       'Thursday, August 1, 1963', 'Sunday, August 1, 2010',
       'Sunday, May 1, 1955', 'Sunday, November 1, 2015',
       'Monday, September 1, 2008', 'Tuesday, August 1, 2017',
       'Monday, May 1, 2017', 'Sunday, May 1, 2016',
       'Thursday, January 1, 1920', 'Thursday, February 1, 1973',
       'Tuesday, January 1, 1918', 'Saturday, February 1, 1969',
       'Thursday, October 1, 1964', 'Tuesday, February 1, 1977',
       'Friday, May 1, 2009', 'Thursday, March 1, 1956',
       'Wednesday, August 1, 2012', 'Tuesday, October 1, 1935',
       'Saturday, July 1, 1972', 'Thursday, July 1, 1965',
       'Wednesday, April 1, 2009', 'Wednesday, June 1, 1927',
       'Friday, June 1, 1962', 'Sunday, October 1, 2006',
       'Friday, March 1, 2013', 'Saturday, June 1, 1963',
       'Thursday, May 1, 1969', 'Thursday, August 1, 2013',
       'Saturday, March 1, 1930', 'Saturday, December 1, 2012',
       'Friday, October 1, 1943', 'Tuesday, March 1, 2011',
       'Saturday, January 1, 1916', 'Sunday, July 1, 1962',
       'Wednesday, November 1, 2006', 'Tuesday, February 1, 2011',
       'Saturday, January 1, 2011', 'Sunday, January 1, 1928',
       'Thursday, November 1, 2007', 'Friday, March 1, 1957',
       'Wednesday, July 1, 2020', 'Friday, June 1, 1951',
       'Sunday, April 1, 2007', 'Thursday, January 1, 2015',
       'Thursday, February 1, 2007', 'Friday, January 1, 1915',
       'Wednesday, January 1, 1902', 'Thursday, March 1, 2007',
       'Tuesday, July 1, 1975', 'Monday, January 1, 1923',
       'Monday, January 1, 1912', 'Tuesday, May 1, 2007',
       'Saturday, January 1, 1910', 'Friday, January 1, 1909',
       'January 1835', 'January 1848', 'Wednesday, November 1, 1967',
       'Thursday, December 1, 1960', 'Thursday, June 1, 1950',
       'Tuesday, December 1, 2009', 'Sunday, January 1, 1922',
       'Sunday, July 1, 2007', 'Saturday, January 1, 1921',
       'Saturday, May 1, 1965', 'January 1873', 'January 1889',
       'Wednesday, March 1, 1967', 'January 1895',

In [57]:
def book_type(yr):
    if yr > 'Friday, December 1, 1995' :
        return 'new'
    else:
        return 'old'

In [61]:
df['book type'] = df['Publish Date'].apply(lambda x : book_type(x))

In [59]:
df

,Title,Authors,Description,Category,Publisher,Publish Date,Price,book type
0,Goat Brothers,"By Colton, Larry",NaN,"History , General",Doubleday,"Friday, January 1, 1993",Price Starting at $8.79,new
1,The Missing Person,"By Grumbach, Doris",NaN,"Fiction , General",Putnam Pub Group,"Sunday, March 1, 1981",Price Starting at $4.99,new
2,Don't Eat Your Heart Out Cookbook,"By Piscatella, Joseph C.",NaN,"Cooking , Reference",Workman Pub Co,"Thursday, September 1, 1983",Price Starting at $4.99,new
3,When Your Corporate Umbrella Begins to Leak: A...,"By Davis, Paul D.",NaN,NaN,Natl Pr Books,"Monday, April 1, 1991",Price Starting at $4.99,new
4,Amy Spangler's Breastfeeding : A Parent's Guide,"By Spangler, Amy",NaN,NaN,Amy Spangler,"Saturday, February 1, 1997",Price Starting at $5.32,new
...,...,...,...,...,...,...,...,...
103077,Build 3 Super Serving Carts,By Chuck Hampton,NaN,NaN,ENDesigns Inc.,"Wednesday, January 1, 1992",Price Starting at $9.97,new
103078,My Land of Israel,"By Nover, Elizabeth Z.",NaN,"Juvenile Nonfiction , People & Places , Middl...",Behrman House,"Friday, May 1, 1987",Price Starting at $4.99,new
103079,Tongues: To Speak or Not to Speak,By Donald W. Burdick,NaN,NaN,Moody Press,"Wednesday, January 1, 1969",Price Starting at $5.29,new
103080,If I'm in charge here why is everybody laughing?,"By Campbell, David P.",NaN,NaN,Argus Communications,"Tuesday, January 1, 1980",Price Starting at $4.99,new
103081,Your First Puppy (Your First Series),"By Carpentier, Marcel",An introduction to the proper care of puppies ...,"Pets , Dogs , General",Tfh Pubns Inc,"Friday, November 1, 1991",Price Starting at $4.99,new

Pandas Visualisation

In [60]:
df.plot()

TypeError: no numeric data to plot